name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        include:
          - rid: win-x64
            name: v2rayN-With-Core
          - rid: win-arm64
            name: v2rayN-arm64-With-Core
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: |
          dotnet publish v2rayN/v2rayN.csproj -c Release -r ${{ matrix.rid }} --self-contained true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: v2rayN/bin/Release/net8.0-windows10.0.17763.0/${{ matrix.rid }}/publish/
